// TODL: add supports for tags
export const habrData = [
  {
    title:
      'PVS-Studio Static Analyzer as a Tool for Protection against Zero-Day Vulnerabilities',
    time: '2019-11-28 07:17:00',
    tags: ['PVS-Studio corporate blog', 'Information Security'],
    link: 'https://habr.com/en/company/pvs-studio/blog/477838/',
    rating: 27,
    rawTime: 'November 28, 2019 at 10:17 AM',
    resources_id: 1,
  },
  {
    title: 'Checking the Ark Compiler Recently Made Open-Source by Huawei',
    time: '2019-12-02 06:39:00',
    tags: ['PVS-Studio corporate blog', 'Open source', 'C++', 'Compilers', 'C'],
    link: 'https://habr.com/en/company/pvs-studio/blog/478282/',
    rating: 24,
    rawTime: 'December 2, 2019 at 09:39 AM',
    resources_id: 1,
  },
  {
    title: 'СodeSide. The new game for Russian AI Cup',
    time: '2019-12-02 16:31:00',
    tags: [
      'Mail.ru Group corporate blog',
      'Abnormal programming',
      'Sport programming',
      'Entertaining tasks',
      'Artificial Intelligence',
    ],
    link: 'https://habr.com/en/company/mailru/blog/478400/',
    rating: 5,
    rawTime: 'December 2, 2019 at 07:31 PM',
    resources_id: 1,
  },
  {
    title: 'Windows Terminal Preview v0.7 Release',
    time: '2019-12-17 07:00:00',
    tags: [
      'Microsoft corporate blog',
      'System administration',
      'GitHub',
      'Development for Windows',
    ],
    link: 'https://habr.com/en/company/microsoft/blog/478166/',
    rating: 2,
    rawTime: 'today at 10:00 AM',
    resources_id: 1,
  },
  {
    title: 'AI-assisted IntelliSense for your team’s codebase',
    time: '2019-11-29 07:00:00',
    tags: [
      'Microsoft corporate blog',
      'Programming',
      'Visual Studio',
      'Machine learning',
      'Artificial Intelligence',
    ],
    link: 'https://habr.com/en/company/microsoft/blog/477104/',
    rating: 2,
    rawTime: 'November 29, 2019 at 10:00 AM',
    resources_id: 1,
  },
  {
    title:
      'Dynamic CDN for Low Latency WebRTC Streaming with Stream Access Control',
    time: '2019-12-02 09:19:00',
    tags: [
      'Flashphoner corporate blog',
      'Website development',
      'Working with video',
      'Programming',
      'Video conferencing',
    ],
    link: 'https://habr.com/en/company/flashphoner/blog/478310/',
    rating: 1,
    rawTime: 'December 2, 2019 at 12:19 PM',
    resources_id: 1,
  },
];
