export const devtoDataMock = {
  result: [
    {
      title: 'Creating a fold out navigation with CSS only',
      path: '/cydstumpel/creating-a-fold-out-navigation-with-css-only-4g9k',
      main_image: 'https://dev-to-uploads.s3.amazonaws.com/i/q19vv.png',
      class_name: 'Article',
      comments_count: 18,
      reading_time: 4,
      language: 'en',
      tag_list: ['CSS', 'Tutorial', 'codepen', 'beginners'],
      positive_reactions_count: 182,
      id: 228410,
      hotness_score: 224837,
      score: 183,
      readable_publish_date: 'Dec 29',
      flare_tag: null,
      user_id: 142415,
      organization_id: null,
      cloudinary_video_url: null,
      video_duration_in_minutes: '0:00',
      experience_level_rating: 6.0,
      experience_level_rating_distribution: 0.0,
      published_at_int: 1577633395,
      user: {
        username: 'cydstumpel',
        name: 'Cyd',
        profile_image_90:
          'https://res.cloudinary.com/practicaldev/image/fetch/s--UnDaCZX_--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/142415/1071926d-4beb-4b29-867c-0aee203cb532.jpeg',
      },
      organization: null,
      _tags: [
        'css',
        'tutorial',
        'codepen',
        'beginners',
        'user_142415',
        'username_cydstumpel',
        'lang_en',
      ],
      objectID: 'articles-228410',
    },
    {
      title: 'Top 4 platforms for learning how to code (2020 edition)',
      path:
        '/realtoughcandy/top-4-platforms-for-learning-how-to-code-2020-edition-e6g',
      main_image: null,
      class_name: 'Article',
      comments_count: 9,
      reading_time: 6,
      language: 'en',
      tag_list: ['education', 'javascript', 'webdev', 'beginners'],
      positive_reactions_count: 180,
      id: 227370,
      hotness_score: 223031,
      score: 181,
      readable_publish_date: 'Dec 27',
      flare_tag: null,
      user_id: 33233,
      organization_id: null,
      cloudinary_video_url: null,
      video_duration_in_minutes: '0:00',
      experience_level_rating: 5.0,
      experience_level_rating_distribution: 5.0,
      published_at_int: 1577444293,
      user: {
        username: 'realtoughcandy',
        name: 'RealToughCandy',
        profile_image_90:
          'https://res.cloudinary.com/practicaldev/image/fetch/s--GXn-wyZL--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/33233/cc496e22-1cfd-4f73-a431-7d15bfbda812.jpg',
      },
      organization: null,
      _tags: [
        'education',
        'javascript',
        'webdev',
        'beginners',
        'user_33233',
        'username_realtoughcandy',
        'lang_en',
      ],
      objectID: 'articles-227370',
    },
    {
      title: 'Some helpful Bash scripts I use daily',
      path: '/aviaryan/some-helpful-bash-scripts-i-use-daily-40bd',
      main_image: null,
      class_name: 'Article',
      comments_count: 18,
      reading_time: 3,
      language: 'en',
      tag_list: ['bash', 'scripting', 'automation'],
      positive_reactions_count: 172,
      id: 226623,
      hotness_score: 221843,
      score: 173,
      readable_publish_date: 'Dec 25',
      flare_tag: null,
      user_id: 24983,
      organization_id: null,
      cloudinary_video_url: null,
      video_duration_in_minutes: '0:00',
      experience_level_rating: 5.0,
      experience_level_rating_distribution: 5.0,
      published_at_int: 1577278810,
      user: {
        username: 'aviaryan',
        name: 'Avi Aryan',
        profile_image_90:
          'https://res.cloudinary.com/practicaldev/image/fetch/s--WExIutgE--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/24983/9ec9bf32-1dfd-4a6b-b377-5682bbf86dce.jpg',
      },
      organization: null,
      _tags: [
        'bash',
        'scripting',
        'automation',
        'user_24983',
        'username_aviaryan',
        'lang_en',
      ],
      objectID: 'articles-226623',
    },
  ],
  nbHits: 1447,
  page: 2,
  nbPages: 67,
  hitsPerPage: 15,
  exhaustiveNbHits: true,
  query: '*',
  params:
    'query=*&hitsPerPage=15&page=2&attributesToHighlight=%5B%5D&tagFilters=%5B%5D&filters=published_at_int%20%3E%201577058620&restrictIndices=searchables_production%2CTag_production%2Cordered_articles_production%2CClassifiedListing_production%2Cordered_articles_by_published_at_production%2Cordered_articles_by_positive_reactions_count_production%2Cordered_comments_production',
  processingTimeMS: 1,
};
